# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cryptoviewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  pod 'SVGParser'
  # Pods for Cryptoviewer

  target 'CryptoviewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoviewerUITests' do
    # Pods for testing
  end

end
